version: '2'
services:
    fixit-app:
        image: fixit
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://fixit-mysql:3306/fixit?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    fixit-mysql:
        extends:
            file: mysql.yml
            service: fixit-mysql
